ente-io/photos-desktop

src/utils/sentry.ts

send environment during sentry  error logging

Improve logging

---

.github/workflows/build.yml

allow manual build

---

package.json
src/config/index.ts

🤦 forgot to change the URL before releasing

fix prod URL

---

README.md

Sibling for https://github.com/ente-io/bhari-frame/pull/28

Mark user contributed ports

---

.github/workflows/build.yml
package.json

adds Pacman target for arch
successfully built

add pacman linux target  

---

src/main.ts

bypass download confirmation and download directly to user "download" directory
tested locally

bypass download confirmation

---

main/preload.ts
main/utils/cache.ts
main/utils/ipcComms.ts

added `CacheStorage` like API to cache files in the bundled app where cache storage is not supported.
tested locally

disk caching support

---

main/utils/cache.ts
main/utils/diskLRU.ts
package.json
yarn.lock

add lru cache eviction strategy

---

main/preload.ts
main/utils/cache.ts

added delete cache API 
tested all the APIs

Delete cache api

---

main/utils/cache.ts

added new cache delete api

---

src/utils/createWindow.ts
src/utils/main.ts

- the icon click makes the hidden window visible
- icon stays on the window close
tested with local build

Fix mac dock icon behaviour

---

package.json

releasing this fix
https://github.com/ente-io/bada-frame/pull/695
https://github.com/ente-io/bhari-frame/releases/untagged-407274adf267111d1d16
tested locally

Release buy subscription fix

---

.gitmodules
package.json
yarn.lock

this fixes the issue where the redirect after subscription purchase was resulting in 404
tested with a local test-release

fix url having query params returning 404

---

src/services/store.ts
src/services/userPreference.ts
src/types/index.ts
src/utils/createWindow.ts
src/utils/main.ts
src/utils/menu.ts

hide dock icon based on user preferences

Hide dock icon option

---

package.json
src/main.ts
src/services/autoLauncher.ts
src/services/autoLauncherClients/linuxAutoLauncher.ts
src/services/autoLauncherClients/macAndWindowsAutoLauncher.ts
src/types/autoLauncher.ts
src/utils/autoLauncher.ts
src/utils/createWindow.ts
src/utils/ipcComms.ts
src/utils/main.ts
src/utils/menu.ts
yarn.lock

Add support for Auto Launch on login

---

.gitmodules
src/api/common.ts
src/api/safeStorage.ts

Add electron types

---

.gitmodules
src/services/fs.ts

-  fix issue files upload through electron , didn't have the same hash as web upload files [d9a37ffd716c25018c0b476c57f6749b7f9b896e]
- update UI submodule to include bug fixes [ente-io/bada-frame/pull/701]
verified that the hash are same now

Fix watch folder issues

---

src/api/watch.ts
src/types/index.ts

fix reported issues 
tested locally

fix watch folder issues-2 

---

.github/workflows/build-old.yml
package.json

https://github.com/ente-io/bhari-frame/releases/tag/untagged-80353867bcaf730391ae
download and basic tested the changes

Release v1.6.5

---

sentry.properties
src/services/sentry.ts

- update the web-app code to include sentry configs in code instead of the environment which can't be set in electron 
- use constants instead of direct string 
tested with a local test-release

Fix error logging

---

package.json

Release v1.6.6

---

src/utils/menu.ts

show open dev tools option in production build

---

src/api/common.ts
src/config/index.ts
src/preload.ts
src/services/appUpdater.ts
src/services/logging.ts
src/services/sentry.ts
src/utils/logging.ts
src/utils/menu.ts

- expose API to write logs to disk
- add report bug help menu option
tested with local build

Log to electron log

---

src/utils/createWindow.ts

add timeout for ready-to-show callback

---

package.json

Release v1.6.7

---

package.json

https://github.com/ente-io/bhari-frame/releases/tag/v1.6.10

Release v1.6.10

---

src/utils/createWindow.ts

remove window background color
tested locally

fix black stripe screen

---

src/api/common.ts
src/preload.ts
src/services/logging.ts
src/utils/ipcComms.ts

adds API to open log directory from UI
tested locally

Open log directory

---

src/api/upload.ts
src/services/fs.ts
src/utils/ipcComms.ts

see https://github.com/ente-io/bada-frame/pull/748

Fix stack overflow issue

---

src/api/system.ts
src/preload.ts
src/services/appUpdater.ts
src/utils/ipcComms.ts
src/utils/menu.ts

see: https://github.com/ente-io/bada-frame/pull/757

App Update Dialog

---

src/services/appUpdater.ts

fix get desktop cuttoff version error logging

---

src/api/common.ts
src/preload.ts
src/services/logging.ts
src/services/sentry.ts
src/utils/ipcComms.ts
src/utils/logging.ts

fetch the sentry Id generated for electron side error logging and use the same in UI side

Sentry id api

---

src/utils/logging.ts

add utc diff in log time

---

.github/workflows/build-old.yml
package.json

bump node version in actions 
test pending

update node version to v16

---

README.md

Only README was changed, so didn't do any specific tests.

Change bhari-frame => photos-desktop in README

---

package.json
src/services/upload.ts

fix zip file paths on windows,by replace windows path separator with POSIX separator 
tested the build on windows machine

fix zip upload windows

---

src/services/ffmpeg.ts
src/services/fs.ts
src/services/heicConverter.ts

- check file exists before reading
- add force flag to rmSync calls to prevent not found errors
tested locally by simulating cases where file not found

Fs better checks

---

package.json
src/utils/processStats.ts
yarn.lock

- add  support to pass IS_TEST_RELEASE env variable to make a debug build
tested locally

Testing setup

---

package.json
src/preload.ts
src/utils/processStats.ts

Add memory usage logging api

---

src/services/diskCache.ts
src/types/cache.ts

added cache entry delete support

---

src/main.ts
src/utils/main.ts

open non app links in an external browser 
- tested for roadmap URL 
- verified payments not affected

open non desktop specific URLs in external browser

---

deployment.md

added `deployment.md` file with updating electron symbol guide

deployment MD

---

src/api/system.ts
src/main.ts
src/preload.ts
src/utils/events.ts

app  in forground event listener

---

package.json

https://github.com/ente-io/photos-desktop/releases/tag/untagged-9d2a671a75cd5b3fd9ad

Release v1.6.22

---

package.json
sentry.properties
src/config/index.ts

update the sentry DSN and project name 
tested with a  release

Update sentry config

---

package.json

https://github.com/ente-io/photos-desktop/releases/tag/untagged-1170574ecb7aca783004

Release v1.6.23

---

package.json

Release v1.6.25

---

package.json

Release v1.6.27

---

package.json
src/config/index.ts

- update file path of UI build files
tested with test release locally

Monorepo UI

---

package.json

- Added support to drag and drop zip  https://github.com/ente-io/photos-web/pull/1098 
- Improved Export https://github.com/ente-io/photos-web/pull/1082 
- Fixed open Export folder for Windows -https://github.com/ente-io/photos-desktop/pull/162/commits/c6183f81341deeb70adadbf145479d5e768d9e85
- https://github.com/ente-io/photos-web/pull/1092
- Files uploaded mobile had location coordinates as (0,0), in case the file didn't have any location data, started ignoring location coordinate (0,0)   https://github.com/ente-io/photos-web/pull/1095
- https://github.com/ente-io/photos-web/pull/1079 
- https://github.com/ente-io/photos-web/pull/1101 
manual QA pending

Release v1.6.28 

---

package.json
src/services/appUpdater.ts

- export and upload related bug fixes 
dev tested and qa testing done

Release v1.6.30

---

package.json

https://github.com/ente-io/photos-desktop/releases/tag/untagged-3257802ce71b0fa7e4e3

release v1.6.31

---

src/api/imageProcessor.ts
src/preload.ts
src/services/imageProcessor.ts
src/utils/ipcComms.ts

rename and update `convertHEIC` API to `convertToJPEG` API 
tested locally

Raw preview

---

package.json

^ title 
- tested by jishnu on windows

Enable deleteAppDataOnUninstall windows option

---

package.json
yarn.lock

^ title 
building successfully and checked we are not affected by any breaking changes

Upgrade electron to latest version

---

package.json

https://github.com/ente-io/photos-desktop/releases/tag/untagged-617baff9f9bd3c1babe6
https://github.com/ente-io/photos-desktop/actions/runs/5363117598

Release v1.6.33

---

package.json
yarn.lock

upgrade node type to version used in electron version we are using

upgrade node type

---

package.json

https://github.com/ente-io/photos-desktop/releases/tag/untagged-6cb90cc6c5a3682abd6d

Release v1.6.36

---

src/services/autoLauncherClients/macAndWindowsAutoLauncher.ts
src/utils/createWindow.ts
src/utils/menu.ts

fixes #206 
The issue was we were maximizing the app on open, which also showed the app.
Fixed it by maximizing only when we are going to show the app 
tested locally

Fix auto launched app not hidden

---

src/main.ts
src/utils/main.ts

- added check to prevent auto-updater setup if installed via brew 
tested locally

Disable electron auto updater app if installed via brew

---

package.json

- #208 
- #209 
- https://github.com/ente-io/photos-web/pull/1294
- https://github.com/ente-io/photos-web/pull/1265
- https://github.com/ente-io/photos-web/pull/1266
- https://github.com/ente-io/photos-web/pull/1268
- https://github.com/ente-io/photos-web/pull/1274
- https://github.com/ente-io/photos-web/pull/1273
- https://github.com/ente-io/photos-web/pull/1272
- https://github.com/ente-io/photos-web/pull/1271
- https://github.com/ente-io/photos-web/pull/1278
- https://github.com/ente-io/photos-web/pull/1277
- https://github.com/ente-io/photos-web/pull/1276
- https://github.com/ente-io/photos-web/pull/1275
- https://github.com/ente-io/photos-web/pull/1281
- https://github.com/ente-io/photos-web/pull/1286
- https://github.com/ente-io/photos-web/pull/1287

Release v1.6.37

---

package.json
yarn.lock

^title 
tested with local build

Reverted back electron to v21

---

src/services/fs.ts

- handle stream error while writing stream to disk 
tested locally

Handle stream error

---

package.json

Release v1.6.39

---

package.json

Release v1.6.40

---

src/api/fs.ts
src/preload.ts
src/services/fs.ts

Add DeleteFile API 

---

src/api/common.ts
src/preload.ts

Download album desktop

---

package.json

https://github.com/ente-io/photos-desktop/compare/v1.6.40...v1.6.41-alpha.4

Release v1.6.41

---

CHANGELOG.md
src/main.ts
src/services/appUpdater.ts
src/services/userPreference.ts
src/utils/main.ts
src/utils/menu.ts

- Added check for update and view changelog option 
- Added changelog for v1.6.41
tested locally

Add check for update and Changelog option

---

src/api/common.ts
src/api/electronStore.ts
src/main.ts
src/preload.ts
src/services/logging.ts
src/services/sentry.ts
src/services/userPreference.ts
src/stores/userPreferences.store.ts
src/types/index.ts
src/utils/ipcComms.ts

- added support to opt out of crash reporting
- tested that toggling error reporting is working properly

Opt out of crash reporting desktop

---

CHANGELOG.md
package.json

https://github.com/ente-io/photos-desktop/compare/v1.6.41...v1.6.43

Release v1.6.43

---

CHANGELOG.md
package.json

- Fixes OOM crashes during file upload [#1379](https://github.com/ente-io/photos-web/pull/1379)

Release v1.6.46

---

CHANGELOG.md
package.json

Release v1.6.47

---

CHANGELOG.md
package.json

Release v1.6.49

---

src/utils/main.ts

Fixed desktop downloaded file had extra dot in name

---

package.json

Update renderer start and build script

---

package.json
src/config/index.ts
src/config/sentry.ts
src/constants/env.ts
src/main.ts
src/services/sentry.ts
yarn.lock

proxy sentry request through reporter worker 
tested locally

Proxy sentry request

---

src/services/clipService.ts

no need to add .exe extension runs without that too on Windows
tested on jishnu machine

improve run command 

---

CHANGELOG.md
package.json
src/api/clip.ts
src/constants/errors.ts
src/services/clipService.ts
src/utils/error.ts

- https://github.com/ente-io/photos-web/pull/1442
- https://github.com/ente-io/photos-web/pull/1448
- https://github.com/ente-io/photos-web/pull/1446
- https://github.com/ente-io/photos-web/pull/1451
- https://github.com/ente-io/photos-web/pull/1453
- https://github.com/ente-io/photos-web/pull/1457
tested locally

Release v1.6.53

---

src/api/electronStore.ts

Clear watch folder on logout

---

.husky/pre-commit

Block commit on main locally using husky 

---

.github/workflows/build.yml
CHANGELOG.md
package.json
src/api/safeStorage.ts

- #271 
- https://github.com/ente-io/photos-web/pull/1445
- https://github.com/ente-io/photos-web/pull/1466
- https://github.com/ente-io/photos-web/pull/1471
- https://github.com/ente-io/photos-web/pull/1470
- https://github.com/ente-io/photos-web/pull/1468
https://github.com/ente-io/photos-desktop/compare/v1.6.53...v1.6.54

Release v1.6.54

---

src/api/cache.ts
src/services/diskCache.ts

- made disk cache limit configurable 
- and remove cacheKey hashing
tested locally

update disk LRU service

---

CHANGELOG.md
package.json
src/services/diskCache.ts
src/types/cache.ts

- #280 
- https://github.com/ente-io/photos-web/pull/1499
https://github.com/ente-io/photos-desktop/compare/v1.6.55...v1.6.56

Release v1.6.56

---

CHANGELOG.md
package.json
src/services/diskCache.ts

fix load issue 
tested locally

Release v1.6.58

---

package.json

^ title 
fixes #282
- Confirmed by the user that's its working properly

configure electron builder to build for arm64 linux

---

CHANGELOG.md
package.json
src/services/diskCache.ts

Release v1.6.59

---

src/services/diskCache.ts
src/services/diskLRU.ts

Ignore file missing error on unlink

---

.github/workflows/build.yml
CHANGELOG.md
package.json

Release v1.6.63

---

src/config/index.ts

update sentry DSN

---

src/config/index.ts

We need to update the DSNs in places that upload sourcemaps

Update Sentry DSN also

---

README.md

https://github.com/ente-io/photos-desktop → https://github.com/ente-io/ente

Add a redirection notice to the new repository

---

.github/ISSUE_TEMPLATE/config.yml

See https://github.com/ente-io/ente/pull/640

Redirect issues to new repository
